sudo: false

language: java
jdk: openjdk11

cache:
  directories:
  - "$HOME/.cache"


deploy:
  # deploy develop as a snapshot
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
    skip_cleanup: true
    on:
      branch: develop
  # deploy master to production
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -P release"
    skip_cleanup: true
    on:
      branch: master
